- name: Setup services server
  hosts: "{{ target }}"
  become: true
  vars:
    connect_token: "{{ lookup('ansible.builtin.env', 'OP_API_TOKEN') }}" 
    ansible_vault: r26avvbe4vsjsx2cnby7jw5unq
  environment:
    OP_CONNECT_HOST: https://op.belanec.eu 
  collections:
    - onepassword.connect
  tasks:
  roles:
    - common
    - frigate
    