- name: Update APT package index
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Upgrade all packages
  apt:
    upgrade: dist

- name: Install packages
  apt:
    name:
      - net-tools
      - python3
      - python3-pip
      - python3-passlib
      - python3-virtualenv
      - lm-sensors
      - dstat
      - smartmontools
    state: present

- name: Install required packages for Docker
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - gnupg
    state: present

- name: Download Docker GPG key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/trusted.gpg.d/docker.asc
    mode: '0644'
  
- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release | lower }} stable"
    state: present

- name: Update APT again after adding Docker repo
  apt:
    update_cache: yes

- name: Install Docker
  apt:
    name: docker-ce
    state: latest

- name: Ensure Docker service is running
  systemd:
    name: docker
    enabled: true
    state: started

- name: Adding existing user '{{ user }}' to group docker
  user:
    name: '{{ user }}'
    groups: docker
    append: yes
